### ISSUE TITLE
Long lines wrapping not working on rel.0.2.9

### ISSUE THREAD

**Issue by IrvinDitz** [askovpen/gossiped#119]
**Describe the bug**
Long lines are not wrapped at the text area border and go beyond visible area.

**Expected behavior**
Long lines are wrapped at the text area border.

**Screenshots**
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/10103010/71519021-e38bc100-28b5-11ea-82fd-c61d9a4d138a.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version: gossipEd-darwin/amd64 0.2.9-181-670ce781

**Comment by askovpen** [comment]
fixed in 0.2.10
