### ISSUE TITLE
Shows blank screen first when enters new area

### ISSUE THREAD

**Issue by ykaliuta** [askovpen/gossiped#166]
When enters new area shows blank screen instead of first message. Moving to the "next" works fine then.

**Comment by askovpen** [comment]
jam, sqush, msg?

**Comment by ykaliuta** [comment]
sqush

**Comment by ykaliuta** [comment]
Either the commit does not help or I did not rebuild it properly (not familiar to golang infra).

**Comment by askovpen** [comment]
test on binary v2.0.20

**Comment by ykaliuta** [comment]
looks working. So how to rebuild it properly? The packaging is very inconvenient for my setup.

**Comment by ykaliuta** [comment]
nvm, found.

**Comment by askovpen** [comment]
how you build? 
git pull origin master, go build (on top level)

**Comment by ykaliuta** [comment]
> how you build?
> git pull origin master, go build (on top level)

I already said, the problem fixed.
