### ISSUE TITLE
Out of bounds access on echoarea entering

### ISSUE THREAD

**Issue by ykaliuta** [askovpen/gossiped#168]
Got

2020/03/08 12:22:22 gossipEd-linux/amd64 2.0-dev started
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0000a6000)
        /home/new/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200204110323-ae3d8cac5e4b/application.go:160 +0x82
panic(0x60b4a0, 0x7ca080)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
github.com/askovpen/gossiped/pkg/msgapi.(*Squish).GetMsg(0xc000496000, 0x7f1400000001, 0x0, 0x0, 0x0)
        /home/new/src/gossiped/pkg/msgapi/squish.go:188 +0xe61
github.com/askovpen/gossiped/pkg/ui.(*App).ViewMsg(0xc0002d8620, 0xa3, 0x0, 0x0, 0x2, 0xc0004714c0, 0x11, 0x2)
        /home/new/src/gossiped/pkg/ui/viewmsg.go:16 +0x7b
github.com/askovpen/gossiped/pkg/ui.(*App).onSelected(0xc0002d8620, 0xa4, 0x0)
        /home/new/src/gossiped/pkg/ui/arealist.go:122 +0x3c4
github.com/askovpen/gossiped/pkg/ui.(*App).AreaList.func3(0xc0004bc3c0, 0xc000088001)
        /home/new/src/gossiped/pkg/ui/arealist.go:87 +0x204
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0004bc3c0, 0xc0000881d0)
        /home/new/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200204110323-ae3d8cac5e4b/box.go:157 +0x75
github.com/rivo/tview.(*Application).Run(0xc0000a6000, 0x0, 0x0)
        /home/new/go/pkg/mod/github.com/rivo/tview@v0.0.0-20200204110323-ae3d8cac5e4b/application.go:245 +0x3d3
github.com/askovpen/gossiped/pkg/ui.(*App).Run(0xc0002d8620, 0x1, 0x1)
        /home/new/src/gossiped/pkg/ui/app.go:39 +0x56
main.main()
        /home/new/src/gossiped/gossiped.go:73 +0x468
zsh: exit 2     gossiped

on entering z2daily

**Comment by ykaliuta** [comment]
[z2daily.sqd.gz](https://github.com/askovpen/gossiped/files/4303047/z2daily.sqd.gz)

**Comment by askovpen** [comment]
z2daily.sqi?

**Comment by ykaliuta** [comment]
> z2daily.sqi?

One more message came so far, but I guess the index should be ok for the one message data
[z2daily.sqi.gz](https://github.com/askovpen/gossiped/files/4305313/z2daily.sqi.gz)

**Comment by askovpen** [comment]
in index(sqi) - two messages, in data(sqd) - one. message dont't have kludges. even msgid.

**Comment by ykaliuta** [comment]
> in index(sqi) - two messages, in data(sqd) - one. 
That I mentioned in the comment.

> message dont't have kludges. even msgid.

it's not an excuse to crash. Kludges (and msgid) are not mandatory by standards.

**Comment by askovpen** [comment]
it's not crash any more.
